### ISSUE TITLE
502 bad gateway error on ALB : statusCode must be numeric

### ISSUE THREAD

**Issue by medicitv** [adamchainz/apig-wsgi#52]
Hey,

having an issue with apig-wsgi on an ALB : I always receive a 502 bad gateway error.
Changing statusCode from a string to a number solve my issue.

This is my working monkey patching :

import apig_wsgi
class Response(apig_wsgi.Response):
    def as_apig_response(self):
        response = super().as_apig_response()
        response['statusCode'] = int(response['statusCode'])
        return response
apig_wsgi.Response = Response

**Comment by adamchainz** [comment]
Hi @medicitv , thanks for the report. I haven't actually had a chance to test the package on ALB, after the ALB Lambda launch the docs basically looked like an API Gateway copy/paste so I figured it was good. Seems it's not 100% the same, but close!

I have added a fixed in #53 and tested it doesn't break API Gateway.

Can you try the new version of the library, 2.1.1, with your ALB Lambda now?

Thanks,

Adam

P.S. next time you are pasting code on GitHub, use triple backticks as per the [guide](https://guides.github.com/features/mastering-markdown/) to preserve the indentation :)
